# Generated by Django 5.1.7 on 2025-03-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit', models.CharField(max_length=1000)),
                ('fruit_name', models.CharField(max_length=1000)),
                ('in_urdu', models.CharField(max_length=1000)),
                ('english_desc', models.CharField(max_length=1000)),
                ('urdu_desc', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'fruits_data',
            },
        ),
    ]
